name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Ant packages
      uses: actions/cache@v3
      with:
        path: ~/.ant/lib
        key: ${{ runner.os }}-ant-${{ hashFiles('**/build.xml') }}
        restore-keys: |
          ${{ runner.os }}-ant-

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PhoneProject
        path: dist/PhoneProject.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: PhoneProject

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
