name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List project contents
      run: |
        pwd
        ls -R

    - name: Check build-impl.xml
      run: cat nbproject/build-impl.xml

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Ant packages
      uses: actions/cache@v4
      with:
        path: ~/.ant/lib
        key: ${{ runner.os }}-ant-${{ hashFiles('**/build.xml') }}
        restore-keys: |
          ${{ runner.os }}-ant-

    - name: Set up CopyLibs
      run: |
        mkdir -p ~/.ant/lib
        cp libs/org-netbeans-modules-java-j2seproject-copylibstask.jar ~/.ant/lib/

    - name: Debug Build Files
      run: |
        echo "Contents of build.xml:"
        cat build.xml
        echo "Contents of nbproject/build-impl.xml:"
        cat nbproject/build-impl.xml
        echo "Contents of nbproject/project.properties:"
        cat nbproject/project.properties

    - name: Set up JDBC driver
      run: |
        if [ -f "libs/mssql-jdbc-12.6.1.jre8.jar" ]; then
          echo "JDBC driver found at libs/mssql-jdbc-12.6.1.jre8.jar"
        else
          echo "JDBC driver not found in libs folder"
          ls -R libs
        fi

    - name: Build with Ant
      run: |
        mkdir -p ~/.ant/lib
        cp libs/org-netbeans-modules-java-j2seproject-copylibstask.jar ~/.ant/lib/
        ant -verbose -noinput -Dlibs.CopyLibs.classpath=~/.ant/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar -Djdbc.driver.jar=libs/mssql-jdbc-12.6.1.jre8.jar -buildfile build.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PhoneProject
        path: dist/PhoneProject.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: PhoneProject

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
