name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List project contents
      run: |
        pwd
        ls -R

    - name: Check build-impl.xml
      run: cat nbproject/build-impl.xml

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Ant packages
      uses: actions/cache@v4
      with:
        path: ~/.ant/lib
        key: ${{ runner.os }}-ant-${{ hashFiles('**/build.xml') }}
        restore-keys: |
          ${{ runner.os }}-ant-

    - name: Set up CopyLibs
      run: |
        mkdir -p ~/.ant/lib
        cp libs/org-netbeans-modules-java-j2seproject-copylibstask.jar ~/.ant/lib/

    - name: Debug Build Files
      run: |
        echo "Contents of build.xml:"
        cat build.xml
        echo "Contents of nbproject/build-impl.xml:"
        cat nbproject/build-impl.xml
        echo "Contents of nbproject/project.properties:"
        cat nbproject/project.properties

    - name: Set up JDBC driver
      run: |
        if [ -f "libs/mssql-jdbc-12.6.1.jre8.jar" ]; then
          echo "JDBC driver found at libs/mssql-jdbc-12.6.1.jre8.jar"
        else
          echo "JDBC driver not found in libs folder"
          ls -R libs
        fi

    - name: Set up project structure
      run: |
        mkdir -p src/test/java
        echo "public class SampleTest { }" > src/test/java/SampleTest.java

    - name: Debug test directory
      run: |
        echo "Contents of src/test/java:"
        ls -R src/test/java
        echo "Contents of SampleTest.java:"
        cat src/test/java/SampleTest.java

    - name: Debug Java environment
      run: |
        java -version
        echo "CLASSPATH: $CLASSPATH"
        echo "ANT_HOME: $ANT_HOME"
        ant -diagnostics

    - name: Manual compile
      run: |
        mkdir -p build/test/classes
        javac -verbose -cp "libs/*:build/classes" -d build/test/classes src/test/java/SampleTest.java > javac_output.log 2>&1 || true
        cat javac_output.log

    - name: Run tests
      run: |
        mkdir -p src/test/java
        ant -debug test > build_output.log 2>&1 || true
        cat build_output.log
        if grep -q "BUILD FAILED" build_output.log; then exit 1; fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PhoneProject
        path: dist/PhoneProject.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: PhoneProject

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./dist
